source("renv/activate.R")
library(here)
library(Zelig)
library(compiler)
library(psych)
library(LaplacesDemon)
library(MASS)
library(rmarkdown)
library(cowplot)
library(ggpubr)
library(linguisticsdown)
library(summarytools)
library(gam)
library(tidyr)
library(ggplot2)
library(matrixStats)

cat("Welcome to Subsampling in Logistic Regression for Model Free scenario 
     comparing the real and the assumed model in Big Data for different alpha.")
