---
params:
  Model_Path:
title: "Best Sub-sampling Method: `r params$Model_Path`"
author: "M.Amalan"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,fig.width = 12,fig.height = 12,message = FALSE,warning = FALSE)
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(LaplacesDemon)
library(xtable)
library(flextable)
library(grid)
library(cowplot)
library(linguisticsdown)
library(ggpubr)
```

```{r load Data}
Old_Labels<-c("Real Model",paste0("Assumed Model ",1:15))
New_Labels<-c("RM",paste0("AM ",1:15))

# Random Sampling
load(here("Non_Identical_r0","Summary",params$Model_Path,"Data","Efficiency",
          "No_Correlated_Covariate_RS.RData"))

for (i in 1:length(Old_Labels)) 
{
  All_Bias$Model[All_Bias$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  All_EMSE$Model[All_EMSE$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  All_Info$Model[All_Info$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  All_MSE_MLE$Model[All_MSE_MLE$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  All_VAR$Model[All_VAR$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i]] <-paste0("RS ",New_Labels[i])
}

RS_Bias<-All_Bias 
RS_EMSE<-All_EMSE
RS_Info<-All_Info
RS_MSE<-All_MSE
RS_MSE_MLE<-All_MSE_MLE
RS_VAR<-All_VAR
RS_ACC<-Accuracy_Data

remove(All_Bias,All_EMSE,All_MSE,All_Info,All_VAR,Accuracy_Data)

# RE Random Sampling
load(here("Non_Identical_r0","Summary",params$Model_Path,"Data","Efficiency",
          "No_Correlated_Covariate_RE_RS.RData"))

for (i in 1:length(Old_Labels)) 
{
  All_Bias$Model[All_Bias$Model==Old_Labels[i]] <-paste0("RE RS ",New_Labels[i])
  All_EMSE$Model[All_EMSE$Model==Old_Labels[i]] <-paste0("RE RS ",New_Labels[i])
  All_Info$Model[All_Info$Model==Old_Labels[i]] <-paste0("RE RS ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i]] <-paste0("RE RS ",New_Labels[i])
  All_MSE_MLE$Model[All_MSE_MLE$Model==Old_Labels[i]] <-paste0("RE RS ",New_Labels[i])
  All_VAR$Model[All_VAR$Model==Old_Labels[i]] <-paste0("RE RS ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i]] <-paste0("RE RS ",New_Labels[i])
}

RE_RS_Bias<-All_Bias 
RE_RS_EMSE<-All_EMSE
RE_RS_Info<-All_Info
RE_RS_MSE<-All_MSE
RE_RS_MSE_MLE<-All_MSE_MLE
RE_RS_VAR<-All_VAR
RE_RS_ACC<-Accuracy_Data

remove(All_Bias,All_EMSE,All_MSE,All_Info,All_VAR,Accuracy_Data)

# OSMAC
load(here("Non_Identical_r0","Summary",params$Model_Path,"Data","Efficiency",
          "No_Correlated_Covariate_OSMAC.RData"))

## mMSE
for (i in 1:length(Old_Labels)) 
{
  All_Bias$Model[All_Bias$Model==Old_Labels[i] & All_Bias$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_EMSE$Model[All_EMSE$Model==Old_Labels[i] & All_EMSE$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Info$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_MSE$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_MSE_MLE$Model[All_MSE_MLE$Model==Old_Labels[i] & All_MSE_MLE$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  All_VAR$Model[All_VAR$Model==Old_Labels[i] & All_VAR$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i] & Accuracy_Data$Type == "mMSE"] <-paste0("OSMAC mMSE ",New_Labels[i])
}

OSMAC_mMSE_Bias<-All_Bias[All_Bias$Type == "mMSE",] 
OSMAC_mMSE_EMSE<-All_EMSE[All_EMSE$Type == "mMSE",]
OSMAC_mMSE_Info<-All_Info[All_Info$Type == "mMSE",]
OSMAC_mMSE_MSE<-All_MSE[All_MSE$Type == "mMSE",]
OSMAC_mMSE_MSE_MLE<-All_MSE_MLE[All_MSE_MLE$Type == "mMSE",]
OSMAC_mMSE_VAR<-All_VAR[All_VAR$Type == "mMSE",]
OSMAC_mMSE_ACC<-Accuracy_Data[Accuracy_Data$Type == "mMSE",]

## mVc
for (i in 1:length(Old_Labels)) 
{
  All_Bias$Model[All_Bias$Model==Old_Labels[i] & All_Bias$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_EMSE$Model[All_EMSE$Model==Old_Labels[i] & All_EMSE$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_Info$Model[All_Info$Model==Old_Labels[i] & All_Info$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_MSE$Model[All_MSE$Model==Old_Labels[i] & All_MSE$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_MSE_MLE$Model[All_MSE_MLE$Model==Old_Labels[i] & All_MSE_MLE$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  All_VAR$Model[All_VAR$Model==Old_Labels[i] & All_VAR$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
  Accuracy_Data$Model[Accuracy_Data$Model==Old_Labels[i] & Accuracy_Data$Type == "mVc"] <-paste0("OSMAC mVc ",New_Labels[i])
}

OSMAC_mVc_Bias<-All_Bias[All_Bias$Type == "mVc",] 
OSMAC_mVc_EMSE<-All_EMSE[All_EMSE$Type == "mVc",]
OSMAC_mVc_Info<-All_Info[All_Info$Type == "mVc",]
OSMAC_mVc_MSE<-All_MSE[All_MSE$Type == "mVc",]
OSMAC_mVc_MSE_MLE<-All_MSE_MLE[All_MSE_MLE$Type == "mVc",]
OSMAC_mVc_VAR<-All_VAR[All_VAR$Type == "mVc",]
OSMAC_mVc_ACC<-Accuracy_Data[Accuracy_Data$Type == "mVc",]

remove(All_Bias,All_EMSE,All_MSE,All_Info,All_VAR,Accuracy_Data)

# OSMAC Model Free
load(here("Non_Identical_r0","Summary",params$Model_Path,"Data","Efficiency",
          "No_Correlated_Covariate_OSMAC_MF.RData"))

## mMSE
All_Bias$Model[All_Bias$Type == "mMSE" & All_Bias$Model == "Model Free Equal"] <-paste0("OSMAC mMSE MF Equal")
All_EMSE$Model[All_EMSE$Type == "mMSE"& All_EMSE$Model == "Model Free Equal"] <-paste0("OSMAC mMSE MF Equal")
All_Info$Model[All_Info$Type == "mMSE"& All_Info$Model == "Model Free Equal"] <-paste0("OSMAC mMSE MF Equal")
All_MSE$Model[All_MSE$Type == "mMSE"& All_MSE$Model == "Model Free Equal"] <-paste0("OSMAC mMSE MF Equal")
All_MSE_MLE$Model[All_MSE_MLE$Type == "mMSE"& All_MSE_MLE$Model == "Model Free Equal"] <-paste0("OSMAC mMSE MF Equal")
All_VAR$Model[All_VAR$Type == "mMSE"& All_VAR$Model == "Model Free Equal"] <-paste0("OSMAC mMSE MF Equal")
Accuracy_Data$Model[Accuracy_Data$Type == "mMSE"& Accuracy_Data$Model == "Model Free Equal"] <-paste0("OSMAC mMSE MF Equal")

All_Bias$Model[All_Bias$Type == "mMSE" & All_Bias$Model == "Model Free UnEqual"] <-paste0("OSMAC mMSE MF UnEqual")
All_EMSE$Model[All_EMSE$Type == "mMSE"& All_EMSE$Model == "Model Free UnEqual"] <-paste0("OSMAC mMSE MF UnEqual")
All_Info$Model[All_Info$Type == "mMSE"& All_Info$Model == "Model Free UnEqual"] <-paste0("OSMAC mMSE MF UnEqual")
All_MSE$Model[All_MSE$Type == "mMSE"& All_MSE$Model == "Model Free UnEqual"] <-paste0("OSMAC mMSE MF UnEqual")
All_MSE_MLE$Model[All_MSE_MLE$Type == "mMSE"& All_MSE_MLE$Model == "Model Free UnEqual"] <-paste0("OSMAC mMSE MF UnEqual")
All_VAR$Model[All_VAR$Type == "mMSE"& All_VAR$Model == "Model Free UnEqual"] <-paste0("OSMAC mMSE MF UnEqual")
Accuracy_Data$Model[Accuracy_Data$Type == "mMSE"& Accuracy_Data$Model == "Model Free UnEqual"] <-paste0("OSMAC mMSE MF UnEqual")

## mVc
All_Bias$Model[All_Bias$Type == "mVc" & All_Bias$Model == "Model Free Equal"] <-paste0("OSMAC mVc MF Equal")
All_EMSE$Model[All_EMSE$Type == "mVc"& All_EMSE$Model == "Model Free Equal"] <-paste0("OSMAC mVc MF Equal")
All_Info$Model[All_Info$Type == "mVc"& All_Info$Model == "Model Free Equal"] <-paste0("OSMAC mVc MF Equal")
All_MSE$Model[All_MSE$Type == "mVc"& All_MSE$Model == "Model Free Equal"] <-paste0("OSMAC mVc MF Equal")
All_MSE_MLE$Model[All_MSE_MLE$Type == "mVc"& All_MSE_MLE$Model == "Model Free Equal"] <-paste0("OSMAC mVc MF Equal")
All_VAR$Model[All_VAR$Type == "mVc"& All_VAR$Model == "Model Free Equal"] <-paste0("OSMAC mVc MF Equal")
Accuracy_Data$Model[Accuracy_Data$Type == "mVc"& Accuracy_Data$Model == "Model Free Equal"] <-paste0("OSMAC mVc MF Equal")

All_Bias$Model[All_Bias$Type == "mVc" & All_Bias$Model == "Model Free UnEqual"] <-paste0("OSMAC mVc MF UnEqual")
All_EMSE$Model[All_EMSE$Type == "mVc"& All_EMSE$Model == "Model Free UnEqual"] <-paste0("OSMAC mVc MF UnEqual")
All_Info$Model[All_Info$Type == "mVc"& All_Info$Model == "Model Free UnEqual"] <-paste0("OSMAC mVc MF UnEqual")
All_MSE$Model[All_MSE$Type == "mVc"& All_MSE$Model == "Model Free UnEqual"] <-paste0("OSMAC mVc MF UnEqual")
All_MSE_MLE$Model[All_MSE_MLE$Type == "mVc"& All_MSE_MLE$Model == "Model Free UnEqual"] <-paste0("OSMAC mVc MF UnEqual")
All_VAR$Model[All_VAR$Type == "mVc"& All_VAR$Model == "Model Free UnEqual"] <-paste0("OSMAC mVc MF UnEqual")
Accuracy_Data$Model[Accuracy_Data$Type == "mVc"& Accuracy_Data$Model == "Model Free UnEqual"] <-paste0("OSMAC mVc MF UnEqual")

# All elements
All_Bias<-rbind(RS_Bias,RE_RS_Bias,
                OSMAC_mMSE_Bias[,!(colnames(OSMAC_mMSE_Bias) %in% "Type")],
                OSMAC_mVc_Bias[,!(colnames(OSMAC_mVc_Bias) %in% "Type")],
                All_Bias[,!(colnames(All_Bias) %in% "Type")])
All_EMSE<-rbind(RS_EMSE,RE_RS_EMSE,
                OSMAC_mMSE_EMSE[,!(colnames(OSMAC_mMSE_EMSE) %in% "Type")],
                OSMAC_mVc_EMSE[,!(colnames(OSMAC_mVc_EMSE) %in% "Type")],
                All_EMSE[,!(colnames(All_EMSE) %in% "Type")])
All_MSE<-rbind(RS_MSE,RE_RS_MSE,
               OSMAC_mMSE_MSE[,!(colnames(OSMAC_mMSE_MSE) %in% "Type")],
               OSMAC_mVc_MSE[,!(colnames(OSMAC_mVc_MSE) %in% "Type")],
               All_MSE[,!(colnames(All_MSE) %in% "Type")])
All_MSE_MLE<-rbind(RS_MSE_MLE,RE_RS_MSE_MLE,
                   OSMAC_mMSE_MSE_MLE[,!(colnames(OSMAC_mMSE_MSE_MLE) %in% "Type")],
                   OSMAC_mVc_MSE_MLE[,!(colnames(OSMAC_mVc_MSE_MLE) %in% "Type")],
                   All_MSE_MLE[,!(colnames(All_MSE_MLE) %in% "Type")])
All_Info<-rbind(RS_Info,RE_RS_Info,
                OSMAC_mMSE_Info[,!(colnames(OSMAC_mMSE_Info) %in% "Type")],
                OSMAC_mVc_Info[,!(colnames(OSMAC_mVc_Info) %in% "Type")],
                All_Info[,!(colnames(All_Info) %in% "Type")])
All_VAR<-rbind(RS_VAR,RE_RS_VAR,
               OSMAC_mMSE_VAR[,!(colnames(OSMAC_mMSE_VAR) %in% "Type")],
               OSMAC_mVc_VAR[,!(colnames(OSMAC_mVc_VAR) %in% "Type")],
               All_VAR[,!(colnames(All_VAR) %in% "Type")])
All_ACC<-rbind(RS_ACC,RE_RS_ACC,
               OSMAC_mMSE_ACC[,!(colnames(OSMAC_mMSE_ACC) %in% "Type")],
               OSMAC_mVc_ACC[,!(colnames(OSMAC_mVc_ACC) %in% "Type")],
               Accuracy_Data[,!(colnames(Accuracy_Data) %in% "Type")])

All_Objects<-ls()
remove(list = All_Objects[startsWith(All_Objects,"OSMAC")])
remove(list = All_Objects[startsWith(All_Objects,"RS")])
remove(list = All_Objects[startsWith(All_Objects,"RE_RS")])
```

# Best Sub-sampling Method : `r params$Model_Path`

# Compare SMSE, EMSE, Variance, Information and Bias for all methods.

```{r Compare All,fig.width=25,fig.height=7}
if(params$Model_Path=="Model_1")
{
  Model_Set_mMSE<-list(c(paste0("OSMAC mMSE AM ",c(1,15)),"OSMAC mMSE RM","RS RM",
                         "OSMAC mMSE MF Equal","OSMAC mMSE MF UnEqual"),
                       c(paste0("OSMAC mMSE AM ",2:5),"OSMAC mMSE RM","RS RM",
                         "OSMAC mMSE MF Equal","OSMAC mMSE MF UnEqual"),
                       c(paste0("OSMAC mMSE AM ",6:10),"OSMAC mMSE RM","RS RM",
                         "OSMAC mMSE MF Equal","OSMAC mMSE MF UnEqual"),
                       c(paste0("OSMAC mMSE AM ",11:14),"OSMAC mMSE RM","RS RM",
                         "OSMAC mMSE MF Equal","OSMAC mMSE MF UnEqual"))
  
  Model_Set_mVc<-list(c(paste0("OSMAC mVc AM ",c(1,15)),"OSMAC mVc RM","RS RM",
                        "OSMAC mVc MF Equal","OSMAC mVc MF UnEqual"),
                      c(paste0("OSMAC mVc AM ",2:5),"OSMAC mVc RM","RS RM",
                        "OSMAC mVc MF Equal","OSMAC mVc MF UnEqual"),
                      c(paste0("OSMAC mVc AM ",6:10),"OSMAC mVc RM","RS RM",
                        "OSMAC mVc MF Equal","OSMAC mVc MF UnEqual"),
                      c(paste0("OSMAC mVc AM ",11:14),"OSMAC mVc RM","RS RM",
                        "OSMAC mVc MF Equal","OSMAC mVc MF UnEqual"))
}

if(params$Model_Path=="Model_2")
{
  Model_Set_mMSE<-list(c(paste0("OSMAC mMSE AM ",c(1,15)),"OSMAC mMSE RM","RS RM",
                         "OSMAC mMSE MF Equal","OSMAC mMSE MF UnEqual"),
                       c(paste0("OSMAC mMSE AM ",2:4),"OSMAC mMSE RM","RS RM",
                         "OSMAC mMSE MF Equal","OSMAC mMSE MF UnEqual"),
                       c(paste0("OSMAC mMSE AM ",5:10),"OSMAC mMSE RM","RS RM",
                         "OSMAC mMSE MF Equal","OSMAC mMSE MF UnEqual"),
                       c(paste0("OSMAC mMSE AM ",11:14),"OSMAC mMSE RM","RS RM",
                         "OSMAC mMSE MF Equal","OSMAC mMSE MF UnEqual"))
  
  Model_Set_mVc<-list(c(paste0("OSMAC mVc AM ",c(1,15)),"OSMAC mVc RM","RS RM",
                         "OSMAC mVc MF Equal","OSMAC mVc MF UnEqual"),
                       c(paste0("OSMAC mVc AM ",2:4),"OSMAC mVc RM","RS RM",
                         "OSMAC mVc MF Equal","OSMAC mVc MF UnEqual"),
                       c(paste0("OSMAC mVc AM ",5:10),"OSMAC mVc RM","RS RM",
                         "OSMAC mVc MF Equal","OSMAC mVc MF UnEqual"),
                       c(paste0("OSMAC mVc AM ",11:14),"OSMAC mVc RM","RS RM",
                         "OSMAC mVc MF Equal","OSMAC mVc MF UnEqual"))
}

Plot_List<-list()

for (i in 1:length(Model_Set_mMSE)) 
{
  All_MSE[All_MSE$Model %in% Model_Set_mMSE[[i]],] %>%
    ggplot(.,aes(x=Subsample_Size,y=MSE,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("MSE")+ggtitle("MSE")->Plot_List[[1]]
  
  All_MSE_MLE[All_MSE_MLE$Model %in% Model_Set_mMSE[[i]],] %>%
    ggplot(.,aes(x=Subsample_Size,y=MSE,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("MSE")+ggtitle("MSE for MLE")->Plot_List[[2]]
  
  All_EMSE[All_EMSE$Model %in% Model_Set_mMSE[[i]],] %>%
    ggplot(.,aes(x=Subsample_Size,y=EMSE,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("EMSE")+ggtitle("EMSE")->Plot_List[[3]]
  
  All_VAR[All_VAR$Model %in% Model_Set_mMSE[[i]],] %>%
    ggplot(.,aes(x=Subsample_Size,y=mean_Variance,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("Variance")+ggtitle("Variance")->Plot_List[[4]]
  
  All_Info[All_Info$Model %in% Model_Set_mMSE[[i]],] %>%
    ggplot(.,aes(x=Subsample_Size,y=mean_Info,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("Information")+ggtitle("Information")->Plot_List[[5]]
  
  All_Bias[All_Bias$Model %in% Model_Set_mMSE[[i]],]%>%
    ggplot(.,aes(x=Subsample_Size,y=mean_Bias,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("Bias")+ggtitle("Bias")->Plot_List[[6]]
  
  All_ACC[All_ACC$Model %in% Model_Set_mMSE[[i]],] %>%
    ggplot(.,aes(x=Subsample_Size,y=Average_Accuracy,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("Average Accuracy")+ggtitle("Average Accuracy")->Plot_List[[7]]
  
  print(ggarrange(plotlist = Plot_List,common.legend = TRUE,nrow=1))
}

Plot_List<-list()

for (i in 1:length(Model_Set_mVc)) 
{
  All_MSE[All_MSE$Model %in% Model_Set_mVc[[i]],] %>%
    ggplot(.,aes(x=Subsample_Size,y=MSE,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("MSE")+ggtitle("MSE")->Plot_List[[1]]
  
  All_MSE_MLE[All_MSE_MLE$Model %in% Model_Set_mVc[[i]],] %>%
    ggplot(.,aes(x=Subsample_Size,y=MSE,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("MSE")+ggtitle("MSE for MLE")->Plot_List[[2]]
  
  All_EMSE[All_EMSE$Model %in% Model_Set_mVc[[i]],] %>%
    ggplot(.,aes(x=Subsample_Size,y=EMSE,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("EMSE")+ggtitle("EMSE")->Plot_List[[3]]
  
  All_VAR[All_VAR$Model %in% Model_Set_mVc[[i]],] %>%
    ggplot(.,aes(x=Subsample_Size,y=mean_Variance,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("Variance")+ggtitle("Variance")->Plot_List[[4]]
  
  All_Info[All_Info$Model %in% Model_Set_mVc[[i]],] %>%
    ggplot(.,aes(x=Subsample_Size,y=mean_Info,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("Information")+ggtitle("Information")->Plot_List[[5]]
  
  All_Bias[All_Bias$Model %in% Model_Set_mVc[[i]],]%>%
    ggplot(.,aes(x=Subsample_Size,y=mean_Bias,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("Bias")+ggtitle("Bias")->Plot_List[[6]]
  
  All_ACC[All_ACC$Model %in% Model_Set_mVc[[i]],] %>%
    ggplot(.,aes(x=Subsample_Size,y=Average_Accuracy,color=Model))+
    geom_point()+geom_line()+scale_colour_viridis_d()+
    theme_light()+xlab("Sub sample size")+
    ylab("Average Accuracy")+ggtitle("Average Accuracy")->Plot_List[[7]]
  
  print(ggarrange(plotlist = Plot_List,common.legend = TRUE,nrow=1))
}
```

